package com.oxygen.managment.oxyavailibility.dao;

public class DaoQueryBuilder {
	
	public static String FIND_USER_BY_ID = "SELECT OAU_MOBILE_NO,OAU_PASSWORD, ENABLED,OAU_NAME,OAU_USER_ID FROM OXY_AVAIL.OAU_USERS WHERE OAU_MOBILE_NO=?";
	public static String FIND_AUTHORITIES_BY_USER_ID = "SELECT B.OAU_MOBILE_NO, A.OAA_AUTHORITY FROM OXY_AVAIL.OAA_AUTHORITIES A, OXY_AVAIL.OAU_USERS B WHERE B.OAU_MOBILE_NO=? AND A.OAA_MOBILENO=B.OAU_MOBILE_NO";
	public static String GENERATE_OXYGEN_CYLINDER_REQUEST="INSERT INTO OXY_AVAIL.OAR_REQUEST " + 
			"(OAR_USERID,OAR_CYLINDER_NO,OAR_REQ_DATE" + 
			",OAR_APPROVAL_STATE,OAR_EFF_START_DATE,OAR_EFF_END_DATE,OAR_REC_START_DATE,OAR_REC_END_DATE,OAR_REQ_STOCK_INCR_CMNT)" + 
			" VALUES (?,?,?,?,CURDATE(),'9999-01-01',CURDATE(),'9999-01-01',?)";
	
	public static String GET_GENERATED_REQUEST_ID="SELECT OAR_REQUEST_ID FROM OXY_AVAIL.OAR_REQUEST ORDER BY OAR_REQUEST_ID  DESC  LIMIT 0, 1";
	
	public static String DELETE_REQUEST_BY_REQUEST_ID = "UPDATE OXY_AVAIL.OAR_REQUEST SET OAR_REC_END_DATE=CURDATE() WHERE OAR_REQUEST_ID = ? ";
	
	public static String SELECT_ACTIVE_REQUEST="SELECT OAU_NAME,OAR_REQUEST_ID,OAR_USERID,"
			+ "OAR_CYLINDER_NO,OAR_REQ_DATE,OAR_APPROVAL_STATE,OAR_EFF_START_DATE,"
			+ "OAR_EFF_END_DATE,OAR_REC_END_DATE FROM OXY_AVAIL.OAR_REQUEST RT "
			+ "INNER JOIN OXY_AVAIL.OAU_USERS USER ON RT.OAR_USERID = USER.OAU_USER_ID"
			+ " WHERE OAR_REC_END_DATE ='9999-01-01' ORDER BY OAR_REQUEST_ID DESC ";
	
	public static String UPDATE_REQUEST_BY_ID = "UPDATE OXY_AVAIL.OAR_REQUEST SET OAR_CYLINDER_NO = ? WHERE OAR_REQUEST_ID = ? ";
	
	
	//registration purpose
	
	public static String REGISTER_USER_TO_USER_TABlE= "INSERT INTO oxy_avail.oau_users(oau_name,oau_mobile_no,oau_password,enabled,OAU_ADMIN_PREV_ASKED) VALUES (?,?,?, true,?)";
			
			
	public static String GRANT_ACCESS_TO_REGISTERED_USER = "INSERT INTO oxy_avail.oaa_authorities (oaa_mobileno, oaa_authority) VALUES (?, ?)" ;
	
	
	public static String APPROVE_REQUEST_STATUS_BY_ID = "UPDATE OXY_AVAIL.OAR_REQUEST SET OAR_REQ_APPROVAL_CMNT = ?,OAR_APPROVAL_STATE = ? ,OAR_REQ_APPROVAL_DATE = CURDATE() WHERE OAR_REQUEST_ID = ? ";
	public static String REJECT_REQUEST_STATUS_BY_ID = "UPDATE OXY_AVAIL.OAR_REQUEST SET OAR_REQ_REJECTION_CMNT = ?, OAR_APPROVAL_STATE = ? ,OAR_REQ_APPROVAL_DATE = CURDATE() WHERE OAR_REQUEST_ID = ? ";
	public static String COMPLETE_REQUEST_STATUS_BY_ID = "UPDATE OXY_AVAIL.OAR_REQUEST SET OAR_REQ_COMPLETION_CMNT = ?,OAR_APPROVAL_STATE = ? ,OAR_REQ_APPROVAL_DATE = CURDATE() WHERE OAR_REQUEST_ID = ? ";
	
	
	

	public static String SELECT_USER_FROM_REQUEST="SELECT USER.OAU_MOBILE_NO, USER.OAU_NAME,OAR_REQUEST_ID,OAR_USERID,"
			+ "OAR_CYLINDER_NO,OAR_REQ_DATE,OAR_APPROVAL_STATE,OAR_EFF_START_DATE,"
			+ "OAR_EFF_END_DATE,OAR_REC_END_DATE FROM OXY_AVAIL.OAR_REQUEST RT "
			+ "INNER JOIN OXY_AVAIL.OAU_USERS USER ON RT.OAR_USERID = USER.OAU_USER_ID"
			+ " WHERE OAR_REC_END_DATE ='9999-01-01' AND OAR_REQUEST_ID = ? ORDER BY OAR_REQUEST_ID DESC ";
			
}
