package com.oxygen.managment.oxyavailibility.dao;

public class DaoQueryBuilder {
	
	public static String FIND_USER_BY_ID = "SELECT OAU_MOBILE_NO,OAU_PASSWORD, ENABLED,OAU_NAME,OAU_USER_ID FROM OXY_AVAIL.OAU_USERS WHERE OAU_MOBILE_NO=?";
	public static String FIND_AUTHORITIES_BY_USER_ID = "SELECT B.OAU_MOBILE_NO, A.OAA_AUTHORITY FROM OXY_AVAIL.OAA_AUTHORITIES A, OXY_AVAIL.OAU_USERS B WHERE B.OAU_MOBILE_NO=? AND A.OAA_MOBILENO=B.OAU_MOBILE_NO";
	public static String GENERATE_OXYGEN_CYLINDER_REQUEST="INSERT INTO OXY_AVAIL.OAR_REQUEST " + 
			"(OAR_USERID,OAR_CYLINDER_NO,OAR_REQ_DATE" + 
			",OAR_APPROVAL_STATE,OAR_EFF_START_DATE,OAR_EFF_END_DATE,OAR_REC_START_DATE,OAR_REC_END_DATE)" + 
			" VALUES (?,?,?,'NAPPR',CURDATE(),'9999-01-01',CURDATE(),'9999-01-01')";
}
